### ISSUE TITLE
Add an easier way to change font size

### ISSUE THREAD

**Issue by gyim** [gyim/breviar-ios#1]
Possible solutions:
* zoom in/out with pinch gesture
* have a button in the menubar/toolbar that displays a popover with zoom controls (and possibly others)

**Comment by gyim** [comment]
This is how it looks like:

![ios simulator screen shot 14 jul 2015 22 51 00](https://cloud.githubusercontent.com/assets/76000/8684849/f57edcc8-2a7a-11e5-927f-063bceeceed4.png)

I downloaded the icons from https://icons8.com. If we want to use these icons, we should also put a link to their site into our About page (see https://icons8.com/license/).

**Comment by breviar-sk** [comment]
Link added into all about.htm files (commit # 4313d04abe22c8edd3a35c3b78a08846036ee3e1 & 7a57cbd7251905e62a5c8dc6b907ce6eecfc2459). Please merge them :) Thank you.
