### ISSUE TITLE
Add a liturgical calendar instead of the date picker

### ISSUE THREAD

**Issue by gyim** [gyim/breviar-ios#11]
The liturgical calendar would serve two purposes:
1. make the (admittedly dummy) date picker easy to use.
2. give users an overview about the current month, so that they can see the past/upcoming celebrations easily (similarly to the [monthly view on breviar.sk](http://breviar.sk/cgi-bin/l.cgi?qt=pdt&d=*&m=2&r=2014&o0=134&o1=5376&o2=21240&o3=1)).

**Comment by breviar-sk** [comment]
1. Leave date picker as is.

2. Use call of CGI module (with day = *) for generating overview of current month.

Screenshots for "month overview" 
![navrh2](https://cloud.githubusercontent.com/assets/842971/7300138/b2ade4ce-e9da-11e4-8ac1-aee4888e4870.png)
![navrh](https://cloud.githubusercontent.com/assets/842971/7300139/b2b0b9e2-e9da-11e4-9a94-e50d6180ec47.png)

included.

**Comment by breviar-sk** [comment]
Note the "day number" was added manually :)

**Comment by gyim** [comment]
This is a good idea (a short list with all the days in the current month), and it's quite easy to implement, so it seems possible to add this to v1.2 (or v2.0, depending on the urgency of the release).

My main concern is navigation: this screen is pushed from the main screen, so the back button on the navigation bar should not be a month chooser, it should be a real back button (otherwise you're stuck on this screen forever :))

We could move the month chooser below the navigation bar, but then the UI would not be consistent: the main screen would have one way to switch dates, and the month screen would have another... Do you have an idea for this?

**Comment by breviar-sk** [comment]
I have no general idea how to implement it in detail - I trust you will design it properly :) Thank you for comment on navigation of my scratch. Of course there must be also real back button but I would vote also for previous/next month navigation somewhere in the top bar.

**Comment by gyim** [comment]
I started playing with this feature a few times, but could not yet figure out a way for the UI to be consistent with the rest of the application... Can we postpone it to the next version? I think the other two features (#1 and #32) are worth a release.

**Comment by breviar-sk** [comment]
OK. I agree :) There are many improvements and fixes (both in cgi code &
typos in html files) in cgi module itself.
Dňa 2.10.2015 23:38 používateľ "Akos Gyimesi" <notifications@github.com>
napísal:

**Comment by gyim** [comment]
Done on the v2 branch.
