### ISSUE TITLE
Fix auto layout warnings

### ISSUE THREAD

**Issue by gyim** [gyim/breviar-ios#2]
There are numerous warnings in logs when opening subscreens or rotating device.

**Comment by breviar-sk** [comment]
Is this issue important for v1.2?

**Comment by kominak** [comment]
Note to myself:

Use automatic table view cell heights + proper hugging/compression resistance for:
* settings cells (no need for separate landscape/portrait/iPhone/iPad cells)
* celebration cells

**Comment by gyim** [comment]
Solved in commit 03dc338d
