### ISSUE TITLE
Different color of title bar (upper & bottom) in night mode?

### ISSUE THREAD

**Issue by breviar-sk** [gyim/breviar-ios#36]
According to well-known Bible app (YouVersion) it would be fine to have different color of title bar (upper & bottom) in night mode. I would prefer the same color as background (or, use system "black").

**Comment by kominak** [comment]
If you want to use the same dark gray as you used in the background, we need to use some thin line to separate the toolbars from the text view...

**Comment by breviar-sk** [comment]
By the way, when page is scrolled (with pure white background due to setting 'AMOLED') the "empty space" behind (under) the generated prayer IS NOT white but has "default" background color. This is not observable when 'AMOLED' setting is off because the colors are the same. It would be nice if the app default background would be configurable via app settings ('AMOLED' and 'night mode' settings). Is possible to use CSS for background color?

**Comment by kominak** [comment]
The AMOLED stuff is fixed here: https://github.com/gyim/breviar-ios/pull/45.

**Comment by kominak** [comment]
Also the rest of this ticket is resolved in #45 - changing the top and bottom toolbars' colors. Main menu is still brown&yellow so when you get back from the prayer screen you'll get proper colors, too.

**Comment by gyim** [comment]
Great, thanks for this fix!
