### ISSUE TITLE
Add a simpler way to skip to Today

### ISSUE THREAD

**Issue by gyim** [gyim/breviar-ios#4]

**Comment by breviar-sk** [comment]
Maybe after solving issue #11 this will be obsolete.

**Comment by gyim** [comment]
Implemented by "Today" links in the top toolbar (only shown if we are not on the current day, and in date picker)

![skip_to_today1](https://user-images.githubusercontent.com/76000/127718719-4a77ffd7-d83b-4607-b6e1-0c34ef174278.png)
![skip_to_today2](https://user-images.githubusercontent.com/76000/127718725-771e56cd-3564-4e00-824f-e4f8c4fe2727.png)
