### ISSUE TITLE
Broken nav bar hiding in iOS 11

### ISSUE THREAD

**Issue by ostatnicky** [gyim/breviar-ios#46]
When I'm in prayer screen I'm not able to hide nav bar and tab bar with tap. Still tapping but nothing hiding. This issue becomes with iOS 11.

**Comment by breviar-sk** [comment]
Tested on these configurations:

- iPad iOS 11 + app v 1.3: OK

- iPhone iOS 11 + app v 1.4 (beta1): OK

- iPhone iOS 9 + app v 1.4 (beta1): OK

Please add more details of the issue. Thank you.

**Comment by ostatnicky** [comment]
Weird, it's ok for me now. It happen only once and I'm using the app every day. Not able to reproduce it. Ok, closing the issues.
