### ISSUE TITLE
Lock screen after period of inactivity

### ISSUE THREAD

**Issue by breviar-sk** [gyim/breviar-ios#50]
Currently, the application does not lock screen which is useful for longer prayer (or meditative praying). But when user forgets to close the app (pressing home button for example) or otherwise exit from it, the screen still remains active especially when user falls asleep :)

App should contain some time period of inactivity after which screen is locked (possibly longer than default iOS setting).

**Comment by breviar-sk** [comment]
Maybe user could choose:

Lock screen after period of inactivity:

- 5 minutes

- 10 minutes

- 1 hour

- never

**Comment by gyim** [comment]
I think this solution (re-enabling timer after 30 minutes) is a good start. It will prevent the battery to drain if somebody falls asleep, and will prevent auto locking in most cases.
