### ISSUE TITLE
Support showing / hiding alternatives

### ISSUE THREAD

**Issue by gyim** [gyim/breviar-ios#51]
Support these links, preferably without reloading / re-scrolling page:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/76000/35778623-0afe784c-09c1-11e8-8e5d-f7c37edb4392.png">

**Comment by gyim** [comment]
@breviar-sk Could you explain how to show these links? Also, what additional options could be relevant here in Settings? (I think the default is to show all the alternatives without these links, maybe this could be an option)

**Comment by breviar-sk** [comment]
Bit option component BIT_OPT_2_ROZNE_MOZNOSTI added (commit # afe64c5c). When switched ON, prayer texts will contain these red hyperlinks = various options directly in prayers.
