### ISSUE TITLE
Review Hungarian translations

### ISSUE THREAD

**Issue by gyim** [gyim/breviar-ios#52]
- [ ] Review commit 178195048065daf9ed813a58f064836127b08a4b. I think these translations are incorrect
- [ ] Fix links that show/hide alternatives (e.g. `rubrikák elrejtése` instead of `elrejtés rubrikák`)

**Comment by breviar-sk** [comment]
To commit # 17819504: It is probably contra-intuitive but it respects printed edition. Common parts for virgins have heading "For virgins" with special cases "For multiple virgins". (One Hungarian priest forced me to comply with printed edition.) So even for one virgin, it is necessary to state "for virgins"; for more virgins: "for multiple/more virgins".

**Comment by breviar-sk** [comment]
To commit # 1781950: Ad "egyháztanító" change: You are right that this title (Teacher of the Church) is used for St Thomas or St Theresa. This is "of3.3". Here ("of3.15" and "of3.16") was indeed mistake. This title (nevelő) is used for few saints, there is only one case when this is the only option: Emiliáni Szent Jeromos (Feb 8th).

**Comment by breviar-sk** [comment]
Links that show/hide alternatives: currently, there is no language-dependency in generating these links:

sprintf(popis_show, "%s %s", html_text_option_skryt[_global_jazyk], html_text_opt_1_rubriky[_global_jazyk]);
sprintf(popis_hide, "%s %s", html_text_option_zobrazit[_global_jazyk], html_text_opt_1_rubriky[_global_jazyk]);

Unfortunatelly, for magyar language, first must be the subject and after that the show/hide verb. I will fix that someday in the future (sorry that it won't be fixed soon).

**Comment by breviar-sk** [comment]
_Note:_ The same way are these links generated both on the web and for Android app for more than 5 years (nobody wrote me about that yet so I hope it is not so big error).
