### ISSUE TITLE
Voice output: Add << and >> (section backward/forward) + possibility to add 'pause' on asterisks

### ISSUE THREAD

**Issue by breviar-sk** [gyim/breviar-ios#55]
Enhance voice output functionality by these two improvements:

1. Adding << and >> (section backward/forward) into system navigation after voice output is started.
1. Adding possibility to indicate that voice output should make small 'pause' on asterisks in psalmody.

1: Text (generated HTML) contains empty divs indicating sections – useful when we would implement “skip forward/backward” functionality.
 
These div’s are not displayed, they are just inside HTML as follows:
 
`<div class="tts_section"></div>`
 
Of course, side effect should be that section is interpreted as pause, thus, small pause is inserted (2 seconds?).

2: Spans indicating small pauses for breathing used in psalmody at the end of lines – long [1-2 seconds] pause on asterisks (*) and short [approx. 1 second] pause on crosses (†).
 
I was not able to us divs because they would destroy formatting so I have decided to use spans. These spans are embracing specified symbol (which itself is displayed) as follows:
 
`<span class="tts_pause">*</span>`
or
`<span class="tts_pause_short">†</span>`

Android version has implemented switch for the 2nd point (thus, these pauses are optional and can be switched off).

**Comment by breviar-sk** [comment]
Just one note: This TTS stuff is exported ONLY for switched ON “voice output” switch.

**Comment by breviar-sk** [comment]
Note: When exporting HTML for voice output (switch ON), spans (for * and + in psalmodies etc.) are exported but symbols (asterisks & crosses) theirselves are not exported (not to be read).

**Comment by gyim** [comment]
Prev/next buttons are implemented. Handling pauses is a bit more work, created #72 as a follow-up.
