### ISSUE TITLE
For Czech application, add Dominican's breviary

### ISSUE THREAD

**Issue by breviar-sk** [gyim/breviar-ios#57]
For Czech application, add Dominican's breviary in the following manner:

- Technically, in CGI-module-breviary there are the following different languages "cz" and "c2" (Czech and Czech Dominicans). This has both historical and technical reason: they use different translation of Psalms, Canticles, and Hymns.

- iOS app GUI will be the same for CGI-module-breviary languages "cz" and "c2" (Czech and Czech Dominicans).

- Add switch for "language" into menu with only two options: "cz" and "c2".

If the above is complicated, I suggest to create another application (technically in Czech AppStore) for Czech-Dominicans.

**Comment by gyim** [comment]
@breviar-sk I added the language chooser into the Czech app with two options (Czech and Czech Dominican). Unfortunately, the strings on the UI (e.g. prayer names on main screen) must be the same for the moment: we have to use standard ISO language codes. Is it a problem? I saw a few minor differences between the Czech and Czech Dominican strings.

**Comment by breviar-sk** [comment]
I think both for Czech (ordinary) and Czech Dominicans it would be problem. They use different terminology even for the basic terms (vespers vs. evening prayer)...

**Comment by gyim** [comment]
OK, I will create a workaround for Czech Dominicans then. It seems that on the UI (MainStoryboard.strings) only the prayer names are different. I will move these names to Breviar.strings and translate them explicitly. And I can probably have two Breviar.strings-like file in Czech easily (the name "Breviar.strings" file is loaded by our code. The MainStoryboard.strings is handled automatically by the iOS framework)
