### ISSUE TITLE
Remember hyperlink settings

### ISSUE THREAD

**Issue by gyim** [gyim/breviar-ios#58]
Everytime user clicks on those new red hyperlinks within prayer, changes in option settings (which apply immediatelly – new prayer is generated with these settings) should remember for “global settings”.
 
Example:

- Situation: Settings have switch “Gospel canticles” OFF. (Thus, Benedictus, Magnificat are NOT displayed within prayers.)
- Open morning prayer (or evening prayer).
- Scroll down as if you prayed.
- Click “display” next to Benedictus/Magnificat.
- Corresponding gospel canticle is displayed (as full text).
- Return to main screen (as if you finished the prayer).
- Open Settings: switch “Gospel canticles” is still OFF. (Thus, Benedictus, Magnificat will NOT displayed within prayers even you have switched that wehn you prayed before.)

**Comment by gyim** [comment]
@breviar-sk Could you give me some direction with this feature? The problem is that these links modify the o1..o5 values, but the options in Settings use verbose option names (e.g. of1c). In order to remember these settings, I would either need to "decode" these o1..o5 values to find and modify the corresponding options in Settings, or modify Settings to use o1..o5 using bitfields.

What do you suggest? Is there an easy way to check in the code where an option like "of1c" translates to bits in "o1"?

**Comment by breviar-sk** [comment]
Calling the app with main parameter p, value xml, returns XML with many infos (we already parse them). See the <Options> element with whole content.
Example:

o1 has actually value 5376, individual bit-component items are listed as separate sub-elements

<Opt1PrayerPortions Value="5376" Name="o1" ForceName="of1" Text="možnosti pre výsledné modlitby">

<BitOpt1Canticles Id="4" ForceName="of1c" Text="evanjeliové chválospevy (Benediktus, Magnifikat, Nunk dimittis)">0</BitOpt1Canticles>

Note the Text value will be displayed according to selected language (param j=hu for instance).

Here Id means real value (Id = 4 means 2^2 i. e. 3rd rightmost bit (numbered from 1); Id = 1024 for of1prz means 2^10 i.e. 10th bit). Just suffice to split 5376 to binary values.

**Comment by gyim** [comment]
Implemented in v2
