### ISSUE TITLE
Create revamped UI (v2)

### ISSUE THREAD

**Issue by gyim** [gyim/breviar-ios#64]
The current UI implementation is very old, and unfortunately, some key parts like the webview is using a deprecated API, so it is not easy to push an update to the App Store. So I started to re-implement the UI based on SwiftUI. The hope is that it will be much easier to develop and modify than the current, Objective-C + UIKit based app.

This ticket serves as a TODO list to create the existing functionality in the new branch (v2):

# Features

## Main screen

- [x] Show selected date dynamically
- [x] Show celebrations with the proper liturgical color
- [x] Show prayer list
- [ ] Support compact prayer list
- [x] Show Settings link
- [x] Show About link
- [x] Smooth animations between days

## Date picker

- [x] Implement prev/next day buttons in main screen
- [x] Show full month in a modal dialog (calendar button)
- [x] Implement prev/next month buttons in calendar picker
- [x] Implement shortcut to today

## Prayer screen

- [x] Show prayer text in web view
- [x] Toggle navigation bar on tap event
- [x] Increase / decrease font size via toolbar
- [x] Support modifier links
- [x] Support Mary antiphones

## Settings

- [x] Implement settings from CGI XML output
- [x] Save settings to user defaults
- [x] Add font chooser

## Language support

- [x] Add language chooser to Settings
- [x] Use appropriate CGI URL for each language
- [x] Use translatable strings on UI
- [x] Translate date format
- [x] Select language at first startup

## Connectivity

- [x] Fetch data online
- [x] Fetch data offline
- [x] Switch between online/offline mode automatically
- [x] Manual fallback to local/remote mode

## Night mode

- [x] Support global night mode on UI
- [x] Select night mode on prayer screen

## Text-to-speech

- [x] Add modal player dialog to prayer screen
- [x] Control TTS via player dialog
- [x] Support background playback
- [x] Add TTS speed to Settings

# Screenshots

![Screen Shot 2021-03-11 at 0 41 43](https://user-images.githubusercontent.com/76000/110713652-90740480-8202-11eb-93bc-d06ff2870377.png)
![Screen Shot 2021-03-11 at 11 25 47](https://user-images.githubusercontent.com/76000/110773266-d78ee380-825c-11eb-9421-f879a7fbd014.png)
![Screen Shot 2021-03-11 at 11 27 17](https://user-images.githubusercontent.com/76000/110773272-d958a700-825c-11eb-8af1-dd00ce633aa4.png)

**Comment by breviar-sk** [comment]
This new GUI looks great!
