### ISSUE TITLE
Pause audio

### ISSUE THREAD

**Issue by borazslo** [gyim/breviar-ios#65]
Some people ask for the possibility to pause the audio.

**Comment by gyim** [comment]
The button that starts audio is actually a pause/play toggle, so this should work already. I added pause/play controls to the lock screen for the next version. In v2.0 we'll have a proper playback dialog for the TTS mode.

**Comment by gyim** [comment]
This is how it will look like. It is also possible to pause/resume with the headset.

![IMG_0781](https://user-images.githubusercontent.com/76000/112071463-17649d80-8b70-11eb-8a6f-b9381fa7d782.PNG)
![IMG_0782](https://user-images.githubusercontent.com/76000/112071466-1a5f8e00-8b70-11eb-9e17-220333ec28c5.PNG)
