### ISSUE TITLE
Does not continue TTS after incoming call

### ISSUE THREAD

**Issue by borazslo** [gyim/breviar-ios#67]
After an incoming call the app does not continue the text from the point it has stopped. Once upon a time this feature has worked well.

> Az lenne a problémám, hogy mivel sokat utazók ezért valamikor az autóban imádkozom hogy olvastatom fel a Zsolozsma át. Annak idején hogyha hívott valaki mondjuk imádság közben akkor onnan folytatta ahonnan abbahagytam, most ez nincs így. Olyan jó lenne hogyha ismételten így lenne. Illetve hogyha leválasztottam valami miatt és visszatettem akkor onnan folytatta ahol abbahagyta.

iPhone 8
version: 1.6 (9c12f5a9)

**Comment by gyim** [comment]
Thanks for the report. It's probably related to a bug that was also reported recently: the prayer screen is reset when the phone is locked/unlocked on the prayer screen. I'll keep this bug open, it's probably an easy fix on the v1 branch.

**Comment by gyim** [comment]
Fixed in latest TTS implementation.
