### ISSUE TITLE
Support bigger font sizes for iPad

### ISSUE THREAD

**Issue by gyim** [gyim/breviar-ios#76]
- Allow an even bigger font size for iPad
- Keep the current options for iPhone. There is probably no point in having 64px font sizes there.

**Comment by breviar-sk** [comment]
Users who installed the app on Mac (I didn't know that this is also possible) also asking for bigger font sizes.

**Comment by gyim** [comment]
Increased max font size. I think this should be enough even if the iPad is put on a remote table:

![image](https://github.com/user-attachments/assets/5786227e-8529-4aa9-b615-a0eaa7d8d26c)
